version: "3"
services:
  backend:
    build: ./backend
    container_name: 'back_superheroes'
    command: sh -c 'python app.py'
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/backend
    depends_on:
      - "base_mongo"
    
  base_mongo:
    container_name: 'mongo_supers'
    image: mongo
    ports:
      - "27017:27017"
  
  frontend:
    build: ./frontend
    container_name: 'frontend_superheroes'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    
    volumes:
      - ./frontend:/frontend
    
    depends_on:
      - "backend"
    stdin_open: true

    tty: true